import Head from "next/head";
export default function Path1() {
  return (
    <>
      <Head>
        <title>테스트 사이트맵 - path1</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>path1</div>
    </>
  );
}
