import Head from "next/head";
export default function Path2() {
    return (
        <>
            <Head>
                <title>테스트 사이트맵 - path2</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <header>
                <h1>Welcome to Our Path 2 site</h1>
                <nav>
                    <ul>
                        <li><a href="/home">Home</a></li>
                        <li><a href="/about">About Us</a></li>
                        <li><a href="/services">Services</a></li>
                        <li><a href="/contact">Contact</a></li>
                        <li><a href="/blog">Blog</a></li>
                    </ul>
                </nav>
            </header>

            <section className="hero">
                <h2>Discover Our Services</h2>
                <p>We offer the best services to help your business grow.</p>
                <img src="https://via.placeholder.com/600x400" alt="Service image" />
            </section>

            <section className="about">
                <h2>About Us</h2>
                <p>We are a company dedicated to helping businesses improve their online presence.</p>
                <p>Founded in 2024, we have worked with various clients worldwide to boost their digital strategies.</p>
            </section>

            <section className="blog-preview">
                <h2>Latest Blog Posts</h2>
                <article>
                    <h3><a href="/blog/post1">How to Improve Your Website SEO</a></h3>
                    <p>Learn the best SEO practices to make your website rank higher on search engines.</p>
                </article>
                <article>
                    <h3><a href="/blog/post2">Top 5 Web Design Trends for 2025</a></h3>
                    <p>Stay ahead of the curve with the latest web design trends for the upcoming year.</p>
                </article>
            </section>

            <footer>
                <p>© 2024 Fake Company, All rights reserved.</p>
            </footer>
        </>
    );
}
